README.md
This is a test PR to ensure that 2 approvals are required before merging any changes to the main branch.
=> DC-119: Add Data Catalog mission

.github/workflows/publish.yml
Enable deploying to Terra dev environment!
=> DC-141: Enable deploy to dev

.github/workflows/build-and-test.yml, .github/workflows/nightly-tests.yml, .github/workflows/publish.yml
Simplify our actions by using the built in Gradle cache?
=> DC-141: Fix broken gradle cache

README.md, docs/Brewfile, docs/getting-started.md
Adds sections in the README for building and testing code, and adds a getting started document for totally new team members.
=> DC-240: First pass at README and getting started docs

README.md
Some nits I noticed in the README when it was rendered.
=> DC-240: Fix wording and spacing nits

.github/workflows/build-and-test.yml
I think this should fix the GitHub action issue with SonarQube
=> DC-251: Include GitHub token

.github/workflows/build-and-test.yml
Also pull out the `SONAR_TOKEN` for clarity and consistency
=> DC-251: Group scanners and tests together

LICENSE
Gabe recommended using BSD3-clause instead.
=> DC-150: Add BSD3-clause license

integration/src/main/resources/configs/integration/ListDatasets.json, integration/src/main/resources/configs/perf/ListDatasets.json, integration/src/main/resources/testusers/admin.json, integration/src/main/resources/testusers/scarlett.json, integration/src/main/resources/testusers/user.json, settings.gradle
Copied the structure that existed for Scarlett Flowerpicker - Just updated the userEmail field. Please let me know if I'm missing something!
=> [DC-218] Added two data catalog test user accounts

common/openapi.yml
We're in production now and I noticed this little nit.
=> DC-158: Nit to fix sentence in warning

scripts/hca/README.md
As I was debugging DC-222 I came across this issue.
=> DC-222: Add missing .py in README.md

scripts/catalog-tests/resources.json
Rename collection from HCA to TDC to avoid confusion with other dev data.
=> DC-222: Update python catalog test resources

.github/workflows/nightly-tests.yml
I think this was accidentally left out in the last PR (https://github.com/DataBiosphere/terra-data-catalog/pull/107)
=> DC-360: Bugfix for TEST_ENV

rawls-client/swagger.gradle, service/src/main/java/bio/terra/catalog/rawls/RawlsService.java, service/src/main/java/bio/terra/catalog/service/DatasetService.java, service/src/test/java/bio/terra/catalog/rawls/RawlsServiceTest.java, service/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
Data preview seems to be working and all tests are complete!
=> DC-347: Preview data for workspaces

.github/workflows/build-and-test.yml, .github/workflows/nightly-tests.yml, .github/workflows/trivy.yml
Trivy success: https://github.com/DataBiosphere/terra-data-catalog/actions/runs/2966902191
=> DC-527: Separate Trivy from other Github actions

.github/workflows/build-and-test.yml, .github/workflows/nightly-tests.yml, .github/workflows/trivy.yml
Requires https://github.com/DataBiosphere/terra-data-catalog/pull/122 to be merged.
PR action success: https://github.com/DataBiosphere/terra-data-catalog/actions/runs/3003505031
Trivy success: https://github.com/DataBiosphere/terra-data-catalog/actions/runs/3003512905
=> DC-527: Enable Trivy scan on PR and nightly tests

service/src/main/java/bio/terra/catalog/common/RequestContextCopier.java, service/src/main/java/bio/terra/catalog/service/DatasetService.java, service/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
Making a draft PR to get tests running
=> multithread storage systems

.github/workflows/build-and-test.yml, .github/workflows/integration-tests.yml, .github/workflows/publish.yml, .github/workflows/trivy.yml, docs/getting-started.md
https://broadworkbench.atlassian.net/browse/DC-1004
We should update the github action notifications to send to our new channel.
=> DC-1004: Point to new #dsp-data-exploration slack channel

service/generators.gradle
Address security finding by updating swagger-ui dependency to latest version
=> DT-737: update swagger-ui dependency

integration/src/main/resources/configs/integration/DatasetOperations.json, integration/src/main/resources/configs/integration/DatasetPermissionOperations.json, integration/src/main/resources/configs/integration/GetStatus.json, integration/src/main/resources/configs/integration/GetVersion.json
https://broadworkbench.atlassian.net/browse/DT-723
=> DT-723: Increase number of retries for Integration tests

.github/workflows/integration-tests.yml
https://broadworkbench.atlassian.net/browse/DT-1089
Changes
- upgrade upload-artifact v3->v4
- copying over the retention that we have set in TDR
Test run on branch: https://github.com/DataBiosphere/terra-data-catalog/actions/runs/12397586855
Successful upload:
=> DT-1089 - Upgrade Upload Artifact v3 -> v4
