- .github/workflows/tag.yml
Per the Semantic Versioning standard, the MINOR version should be bumped when you add functionality in a backwards compatible manner.
> DC-116: Bump MINOR instead of PATCH

- .github/workflows/tag.yml
- settings.gradle
~The tag operation adds a `-` to the suffix so the GitHub action input doesn't need to have it.~
The `SNAPSHOT` suffix isn't necessary after all, see comment below.
> Fix tag workflow suffix

- .github/workflows/publish.yml
As we are no longer using versioning with `-SNAPSHOT`, all artifacts are considered ready for release, so switch to the corresponding repository
> DC-229: Fix artifactory publish

- client/artifactory.gradle
Add the environment variable to the Artifactory gradle to ensure we can override the repo key.
> DC-229: Fix Artifactory gradle

- integration/build.gradle
- integration/src/main/java/scripts/client/CatalogClient.java
- integration/src/main/java/scripts/testscripts/GetStatus.java
- integration/src/main/java/scripts/testscripts/GetVersion.java
- integration/src/main/java/scripts/testscripts/ListDatasets.java
- integration/src/main/java/scripts/utils/CatalogClient.java
- integration/src/main/resources/servers/catalog-local.json
- integration/src/main/resources/servers/catalog-perf.json
Now that testrunner has a server config for catalog, use it instead of policy manager.
> DC-233: update to use testrunner field

- .github/workflows/build-and-test.yml
- buildSrc/build.gradle
- service/build.gradle
- settings.gradle
This adds source clear and sonarqube scans to our PR tests. Source clear checks for vulnerabilities in .jars that we depend on, and sonarqube runs a number of static code analysis checks on our Java code.
~Note that builds will fail until the GitHub secrets are published once https://github.com/broadinstitute/terraform-ap-deployments/pull/551 is merged.~
> DC-251: Add source clear and sonarqube scanners to build

- .github/workflows/build-and-test.yml
- buildSrc/src/main/groovy/bio.terra.catalog.java-common-conventions.gradle
Add the `test` task to the jacoco gradle target so unit tests are run.
- generate an XML jacoco report for sonarqube
- run unit-tests before sonarqube so XML report is present (not working yet)
- use fetch-depth to checkout target merge branch for sonarqube
The ticket https://broadworkbench.atlassian.net/browse/DC-262 tracks the remaining work to upload coverage data using sonarqube.
> DC-253: Run unit tests on PRs

- service/publishing.gradle
This reverts an earlier change where distroless was failing trivy so we switched to the debian base image.
> DC-251: Change back to distroless base image

- buildSrc/src/main/groovy/bio.terra.catalog.java-common-conventions.gradle
- common/openapi.yml
- service/build.gradle
- service/src/main/java/bio/terra/catalog/api/DatasetApiController.java
- service/src/main/java/bio/terra/catalog/common/DaoKeyHolder.java
- service/src/main/java/bio/terra/catalog/common/StorageSystem.java
- service/src/main/java/bio/terra/catalog/datarepo/DatarepoService.java
- service/src/main/java/bio/terra/catalog/iam/SamAction.java
- service/src/main/java/bio/terra/catalog/iam/SamService.java
- service/src/main/java/bio/terra/catalog/service/DatasetService.java
- service/src/main/java/bio/terra/catalog/service/dataset/Dataset.java
- service/src/main/java/bio/terra/catalog/service/dataset/DatasetDao.java
- service/src/main/java/bio/terra/catalog/service/dataset/DatasetId.java
- service/src/test/java/bio/terra/catalog/api/DatasetApiControllerTest.java
- service/src/test/java/bio/terra/catalog/datarepo/DatarepoServiceTest.java
- service/src/test/java/bio/terra/catalog/iam/SamServiceTest.java
- service/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
- service/src/test/java/bio/terra/catalog/service/dataset/DatasetDaoTest.java
- settings.gradle
Add support for CRUD dataset metadata (aka catalog entry) API endpoints.
The existing endpoint `/api/v1/datasets` has four new forms:
- POST `/api/v1/datasets` - creates a new dataset entry in the catalog. The caller provides a JSON body with the storage system, storage ID and catalog entry data. The endpoint returns the catalog ID of the newly created entry.
- GET `/api/v1/datasets/{id}` - return the catalog entry for the dataset
- PUT `/api/v1/datasets/{id}` - replace the catalog entry for the dataset
- DELETE `/api/v1/datasets/{id}` - delete the catalog entry for the dataset
These endpoints check that the calling user has the correct permission in the storage system (currently only TDR) or in SAM for the requested operation.
Note that integration tests are not part of this PR.
> DC-195: create/read/update/delete dataset metadata

- common/openapi.yml
To meet the requirements for SC11 - Authorization Domains, we need to include a warning that all entries will be public to Terra users.
> DC-158: Add warning in OpenApi description

- service/src/main/java/bio/terra/catalog/app/App.java
- service/src/main/java/bio/terra/catalog/datarepo/DatarepoService.java
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/catalog/datarepo/DatarepoServiceTest.java
Fix issue where a user who's been granted admin access to a snapshot wouldn't be able to create a catalog entry
Other minor cleanups
- support up to 1000 snapshots from TDR
- merge `ComponentScan` annotation with `SpringBootApplication` annotation
- remove unused `job` config from `application.yml`
> DC-289: fix issue with TDR permissions in catalog

- .github/workflows/tag.yml
This should fix the issues we've been seeing with the bumper in our actions. It includes the changes from https://github.com/DataBiosphere/github-actions/pull/32
> DC-314: Bump version of bumper to 0.0.6

- render_configs.sh
Previously, we had client ids which lived at the following paths:
1. `secret/dsde/terra/kernel/dev/dev/catalog/swagger-client-id`
2. `secret/dsde/terra/kernel/dev/dev/catalog`
To be consistent with other services, the client id should live at `{service}/swagger-client-id`, however we had an invalid client id at that path and a valid one at the `/catalog` path. This fixes the path issue in the `render-configs.sh` script.
> DC-300: Update the swagger-client-id path

- scripts/db_connect.sh
- scripts/hca/README.md
This script supports running a local proxy to connect to our cloud database. When run, it prints out a JDBC URL that can be pasted into IntelliJ or other SQL IDEs to view tables, etc. Note that this connects using the admin user so it can modify data, so please use it carefully when connecting to the prod database.
> A script to set up a proxy to the catalog postgres database.

- integration/src/main/resources/configs/perf/SnapshotDatasetOperations.json
- integration/src/main/resources/servers/catalog-perf.json
Update the perf catalog tests to use dev TDR instead of perf TDR. The perf TDR environment isn't stable and can't currently be used for catalog tests.
> DC-319: Update perf catalog tests to run using dev TDR

- .github/workflows/nightly-tests.yml
According to https://github.community/t/how-can-you-use-expressions-as-the-workflow-dispatch-input-default/141454/4 , it should be possible to provide a default if none is provided.
> DC-364: Ensure nightly scheduled test has a default env

- .github/workflows/build-and-test.yml
- .github/workflows/nightly-tests.yml
- scripts/manually-run-nightly-tests.sh
This reverts commit b5a479bfb7dd2c23150cf8b553cefec688ed742f.
The GitHub community recommendation will actually break the action. I switched to another solution proposed by @pshapiro4broad .
Also includes the fix from: https://github.com/DataBiosphere/terra-data-catalog/pull/87
> DC-364: Revert "Ensure nightly scheduled test has a default env (#86)"

- docs/getting-started.md
As per retro discussion, update onboarding document with more teams, add more notes about how to join.
> DC-393: add notes about more groups to onboarding document

- scripts/hca/create-hca-collection.py
- scripts/hca/extract-hca-projects.py
- scripts/workspace-conversion/README.md
- scripts/workspace-conversion/workspace-to-dataset.py
Updated workspace generated catalog metadata to include `accessURL`, which contains the link to the corresponding terra workspace.
Also updated the HCA script generated accessURL, and other minor cleanups to the HCA code.
> DC-415: link to workspace support; add workspace URL to dataset metadata

- .github/workflows/build-and-test.yml
Letting the black version float can cause a build failure when the default version installed by `pip install black` doesn't match the version specified by the spotless python plugin.
> DC-422: Pin black version for build

- .github/workflows/nightly-tests.yml
- integration/src/main/resources/servers/catalog-alpha.json
- integration/src/main/resources/servers/catalog-perf.json
- integration/src/main/resources/servers/catalog-staging.json
- settings.gradle
This fixes a few issues with the catalog nightly test:
- add status and env to slack message [DC-427](https://broadworkbench.atlassian.net/browse/DC-427)
- always upload integration test data to QA bucket [DC-429](https://broadworkbench.atlassian.net/browse/DC-429)
- remove unused cluster specifications from integration test configs
- fix issue where failed build could show as green in Slack [DC-360](https://broadworkbench.atlassian.net/browse/DC-360)
message on success:
message on failure:
> DC-427, DC-429, DC-360: nightly test fixes

- docs/getting-started.md
Per a previous team discussion, add resources section to getting started doc for newly onboarding members.
> DC-337: Add resources section to getting started doc

- service/src/main/java/bio/terra/catalog/service/DatasetService.java
- service/src/main/java/bio/terra/catalog/service/dataset/DatasetDao.java
- service/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
- service/src/test/java/bio/terra/catalog/service/dataset/DatasetDaoTest.java
Tested to make sure things weren't double listed.
> [DC-419] Admins can list all datasets, even if they don't have permissions on originating resource

- service/build.gradle
This library doesn't seem to be necessary to build or run the project and has a vulnerability.
> DC-450: Remove jstl library

- integration/src/main/java/scripts/testscripts/DatasetOperations.java
Note: The jib failure is expected. See https://broadinstitute.slack.com/archives/CADU7L0SZ/p1661540427870559 for more info.
> DC-523: Temporarily disable export workspace integration test

- service/publishing.gradle
Since our PR tests don't run the container, no error was generated before the merge.
> DC-542: fix regression where container main class was moved but config wasn't updated

- .github/workflows/build-and-test.yml
- .github/workflows/integration-tests.yml
- .github/workflows/publish.yml
- .github/workflows/tag.yml
- .github/workflows/trivy.yml
- integration/src/main/resources/configs/integration/DatasetOperations.json
Also 
- update actions to newer versions to fix node version warning
- fix issue where failure to start server didn't result in boot logs being printed out
- increase test timeout
> DC-592: GitHub action fixes: remove use of `set-output`

- service/src/main/java/bio/terra/catalog/datarepo/DatarepoService.java
- service/src/test/java/bio/terra/catalog/datarepo/DatarepoServiceTest.java
The code that converts the TDR role to a catalog role doesn't have all possible roles, and roles aren't part of the generated client API as an enum. To avoid an NPE in the future, and to avoid the need to list all possible roles, filter out TDR roles that the catalog doesn't recognize.
> DC-561: fix case where an unknown role from TDR would cause an NPE

- integration/src/main/java/scripts/testscripts/DatasetOperations.java
- integration/src/main/java/scripts/testscripts/DatasetPermissionOperations.java
- service/src/main/java/bio/terra/catalog/service/JsonValidationService.java
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/catalog/service/JsonValidationServiceTest.java
- service/src/test/resources/schema/test.schema.json
Using a fixed file path works in the source tree but doesn't work in the .jar deployment. Changing to use a resource reference using `classpath:` should fix this.
Also
- generate a date-time value on the fly using `Instant`
- add an example of date-time to the test schema
- refactor duplicate code in integration tests that creates dataset metadata
> DC-464: Fix issue where path to resource didn't use a resource path lookup

- integration/src/main/java/scripts/testscripts/DatasetOperations.java
- service/src/main/java/bio/terra/catalog/service/ExternalSystemService.java
- service/src/main/java/bio/terra/catalog/service/dataset/DatasetDao.java
- service/src/test/java/bio/terra/catalog/service/ExternalSystemServiceTest.java
- service/src/test/java/bio/terra/catalog/service/dataset/DatasetDaoTest.java
- add integration CRUD test for external datasets
- update DAO integration tests to use random IDs to avoid test collisions in shared databases like `dev`
- other misc minor changes
> DC-375: external datasets follow-on work

- integration/src/main/java/scripts/testscripts/DatasetPermissionOperations.java
- service/src/main/java/bio/terra/catalog/service/DatasetService.java
- service/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
changed the `UnauthorizedException` to a `ForbiddenException` in the `ensureActionPermission` method
> DC-574: Look at how we return 401 vs 403 errors and fix if necessary

- service/src/main/java/bio/terra/catalog/common/RequestContextCopier.java
- service/src/main/java/bio/terra/catalog/controller/DatasetApiController.java
- service/src/main/java/bio/terra/catalog/service/DatasetService.java
- service/src/test/java/bio/terra/catalog/common/RequestContextCopierTest.java
- service/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
Loading the dataset list from the catalog can take a long time. One of the reasons for this is because we were loading the data from underlying storage systems in sequence. This PR moves that to loading the underlying data in parallel, and then unifying once all the data has been fetched. It does this by using stream parallelism. The added complexity in this PR is a result of Spring Request Context not being copied down to child threads. In this case, because we know this request doesn't close until after all the child threads have finished execution, we want to copy down that request context.
Ticket: https://broadworkbench.atlassian.net/browse/DC-420
Timing:
Before:
curl -X 'GET' 'localhost:8080/api/v1/datasets' -H 'accept: application/json'   0.01s user 0.01s system 1% cpu 1.451 total …
> [DC-420] Sr multithread storage systems

- service/src/main/java/bio/terra/catalog/service/DatasetService.java
- service/src/main/java/bio/terra/catalog/service/dataset/DatasetDao.java
- service/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
- service/src/test/java/bio/terra/catalog/service/dataset/DatasetDaoTest.java
Split out database operation from code that collects datasets from systems, to avoid doing multiple database calls.
The query builder code isn't great, but it is careful to not do any text substitution. It only builds a string that contains `?` placeholders that JdbcTemplate uses to do the actual parameter substitution.
Note that this PR conflicts with with https://github.com/DataBiosphere/terra-data-catalog/pull/154 and will be merged after that PR is merged.
> DC-594: list dataset performance improvement: reduce DB calls

- common/src/main/java/bio/terra/catalog/service/DatasetService.java
- common/src/test/java/bio/terra/catalog/service/DatasetServiceTest.java
- integration/src/main/java/scripts/testscripts/DatasetPermissionOperations.java
With this change, an admin user can again `GET` any dataset in the catalog, even if they don't have access to the storage object in the underlying storage system.
> DC-605: fix permission issue with admin user and dataset GET operation

- README.md
- common/src/main/resources/schema/development/example.json
- service/src/main/resources/api/openapi.yml
- service/src/main/resources/application.yml
- service/src/main/resources/templates/index.html
- settings.gradle
This loads the swagger example content from an external file. It's hardcoded to work for the dataset example in for the dataset PUT operation. A future PR can improve on this work.
What works
- the code intercepts the use of `externalValue` in the PUT request body and loads an example JSON file using HTTP
What doesn't work
- can't get content type from page state
- can't get selected example from page state
- ~code to refresh page after load doesn't seem to work~
- ~example json is loaded as a string, not json object~
> DC-570, DC-622: Add example JSON for request body using openapi's `externalValue` property

- common/src/main/java/bio/terra/catalog/service/BaseStatusService.java
- common/src/main/java/bio/terra/catalog/service/CatalogStatusService.java
- common/src/main/java/bio/terra/catalog/service/StatusCheckService.java
- common/src/test/java/bio/terra/catalog/service/CatalogStatusServiceTest.java
- common/src/test/java/bio/terra/catalog/service/StatusCheckServiceTest.java
- service/src/main/java/bio/terra/catalog/controller/PublicApiController.java
- service/src/test/java/bio/terra/catalog/controller/PublicApiControllerTest.java
This is an attempt to fix the issue where the catalog service starts up in an error state (`/status` endpoint is returning `503`) and never recovers.
One theory is that one of the status checks is taking too long, causing the status check concurrent task to no longer fire. To fix this, I've changed the concurrent task to use `scheduleWithFixedDelay()` instead of `scheduleAtFixedRate()`, which should guard against the case where a status check takes longer than the thread polling interval.
When doing this, I noticed that the timeout for the database check was using 5000 seconds. This check should be very fast so I'm changing the timeout to 1 second instead.
This change also adds unit test coverage for the database status check, and enables performing all the status checks in parallel.
> DC-693: service startup error fix

- .github/workflows/publish.yml
The upgrade to setup-gcloud v1 seems to encourage a separate auth step, per their docs. Trying to see if publish passes with that (need to merge to test because this is not a workflow)
> [DC-698] Try explicit auth before publishing to gcloud

- buildSrc/build.gradle
This also updates a bunch of other plugin versions. It does not update spotbugs because that wasn't a free update, so I decided it was best to keep the changes as minimal as possible, and update that one more intentionally.
> [dc-873][dc-887] upgrade postgresql jre7

- buildSrc/src/main/groovy/bio.terra.catalog.java-common-conventions.gradle
- common/src/main/java/bio/terra/catalog/datarepo/DatarepoService.java
- common/src/test/java/bio/terra/catalog/datarepo/DatarepoServiceTest.java
https://broadworkbench.atlassian.net/browse/DC-839
_______
With the https://github.com/DataBiosphere/jade-data-repo/pull/1581 for data repo, we're switching back to only publishing to one Jakarta backed client. This PR moves your references to the jakarta client back to the main data repo client and bumps to the latest version. This is an effort to alleviate any confusion around upgrading past the last supported datarepo-jakarta-client version.
> DC-839: Move references back to datarepo-client; Upgrade to latest

- service/publishing.gradle
A CVE was discovered in the Debian 11 OS which is the OS used by the 17-distroless image. (It's called distroless but it's really a minimal install; there's no way to make a launchable java container without including some OS distro.) The CVE itself is in the Debian OS, not jre 17, but there is no patch for release 11. The latest distroless image uses Debian 12 as its base image, which has been patched.
In theory this should be a completely safe change to make and shoudln't have any effect on the java code run inside the container. So one possible solution would be change the base image (which is a DSP appsec "blessed" image) to use the OS 12 image. Instead the base image tag was changed, so any dependent repo needs to be updated to use the new base image.
One thing that's been brought up …
> DC-1286: switch to new 17 distroless base image

- .github/CODEOWNERS
- .github/workflows/build-and-test.yml
- .github/workflows/integration-tests.yml
- .github/workflows/publish.yml
- .github/workflows/trivy.yml
Centralizes the configuration for Slack channels in a single variable, and add a CODEOWNERS file so our team is notified on changes.
> [DT-940] Centralize the GitHub Action Slack configuration

- integration/src/main/java/scripts/api/TdrDatasetsApi.java
https://broadworkbench.atlassian.net/browse/DT-957
_______
A recent staging test run failed when attempting to create a TDR dataset. The underlying issue has been noted in this TDR ticket: https://broadworkbench.atlassian.net/browse/DT-958
As a more immediate fix, we can instead use the generic TDR SA for ingest and avoid needing to create a service account. This should help with test flakiness.
> DT-957: Reduce test flakiness - Don't use dedicated ingest service account for TDR dataset create

- service/src/main/resources/templates/index.html
https://broadworkbench.atlassian.net/browse/DT-1022
Similar to https://github.com/DataBiosphere/terra-landing-zone-service/pull/502 and https://github.com/DataBiosphere/terra-workspace-data-service/pull/941 , adds a Content Security Policy to the Swagger UI using a `meta` tag.
The team decided to use this approach instead of the proxy approach since catalog currently has no proxy templating which means that we would either need to modify it for all services or add our own template for catalog, both of which were deemed high risk and low value, especially since catalog is likely to be retired in the near future. Additionally, proxy changes are hard to test, whereas this change was straightforward to test.
Tested with a catalog instance locally, tried endpoints and the login, no errors were …
> [DT-1022] Add CSP to the Swagger UI using meta tag

- .github/workflows/build-and-test.yml
- .github/workflows/integration-tests.yml
- .github/workflows/publish.yml
- .github/workflows/tag.yml
- .github/workflows/trivy.yml
- buildSrc/build.gradle
https://broadworkbench.atlassian.net/browse/DT-1122
- Do not persist credentials if not needed
- Use shell variable expansion instead of [template expansion](https://woodruffw.github.io/zizmor/audits/#template-injection)
- Include `mavenCentral` in gradle build to fix build issues
> [DT-1122] Implement `zizmor` suggestions

- buildSrc/build.gradle
- buildSrc/src/main/groovy/bio.terra.catalog.java-common-conventions.gradle
JIRA ticket https://broadworkbench.atlassian.net/browse/DDO-4132 
**Summary of changes**
Updated the artifact source for this service to read artifacts from Google Artifact Registry instead of JFrog.
**What**
Modified the config to pull artifacts from GAR. No publishing changes were made.
**Why**
This is part of Phase 2 of the artifact migration effort to deprecated JFrog and consolidate artifacts in GAR.
**Testing these changes**
Relied on passing CI checks and tests. Artifact reading-related issues are expected to surface as pipeline failures. For example these jobs [here](https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/15309876591/job/43071753325?pr=222) and [here](https://github.com/DataBiosphere/leonardo/actions/runs/15324072477/job/43114134405?pr=4858 …
> DDO-4132 read from google artifact registry
